### ISSUE TITLE
Search by location does not work for some places

### ISSUE THREAD

**Issue by dkakkar** [cga-harvard/cga-worldmap#223]
This is with respect to http://worldmap.harvard.edu/maps/CHAwellness:
If I search for "Cambridge", I get only Cambridge, UK and not Cambridge, MA, USA. Have to search "Cambridge, MA" to get the one in USA.

**Comment by capooti** [comment]
This is because Cambridge, MA, USA is not part of the gazetteer table. What you could do it is to add a layer containing all the needed place names to the gazetteer. This can be done by uploading a new layer, and adding it in gazetteer from the "attributes" section of the metadata page for a layer:

<img width="856" alt="screenshot 2017-04-10 11 20 51" src="https://cloud.githubusercontent.com/assets/148380/24869009/df5ca81c-1ddf-11e7-95f5-1e1771813d1a.png">

**Comment by capooti** [comment]
Or use Google as the geocoder, which currently seems broken by the new CSS (will file a new ticket about this):

![screenshot 2017-04-10 11 23 03](https://cloud.githubusercontent.com/assets/148380/24869076/1421a26e-1de0-11e7-8455-a2d93886426c.png)

**Comment by blewis** [comment]
I don't think we need to add a special layer for this.
Google should be on by default.  There is something wrong with way we are searching Google because only one result is returned.  It is ok if all Cambridges are returned but now only one is.

**Comment by capooti** [comment]
Ok then, I will try to understand why Google is not used then.

**Comment by capooti** [comment]
@bglewis you are right, it is not needed to add names to the WorldMap gazetteer as also the Google one is used (I have checked it in source code).

Apparently for "Cambridge" Google API geocoder returns just one result, you can test by yourself:
https://maps.googleapis.com/maps/api/geocode/json?address=cambridge

Therefore I am closing the issue as there is nothing we can do against it.

**Comment by capooti** [comment]
@bglewis @dkakkar I have changed the default geocoder from google to geonames.
The geonames one was previously not working because of a configuration problem which I have fixed (geonames username was missing in settings file).
Now there are tons of results for Cambridge :)

<img width="721" alt="screenshot 2017-04-11 17 47 27" src="https://cloud.githubusercontent.com/assets/148380/24932318/f80b2c12-1ede-11e7-8118-de73df9b1781.png">
