### ISSUE TITLE
WorldMap staging - most AfricaMap layers missing

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#561]
http://128.31.22.103/maps/40665/view

**Comment by capooti** [comment]
I believe this was corrupted when I saved it some days ago: there were 3 layers which in GeoServer sent an invalid XML from REST API.
What I did:
1) fixed that layers by saving them in GeoServer
2) used map revisions and restored the map revision before I saved
3) saved the map

About 1) I think there are many layers like that. We will need a script to save them in order to have the XML from REST updated.
