### ISSUE TITLE
Created layer on CAMP staging in new map and cannot see field content on identify

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#611]
Also the cursor is running as if something is happening.  
![image](https://user-images.githubusercontent.com/812849/57788707-8ae02d00-7705-11e9-84d8-8a7b67c01fcf.png)

Then saved map and added another layer and now can see attributes on Identify
![image](https://user-images.githubusercontent.com/812849/57788940-fb874980-7705-11e9-99da-19a0bd5815e2.png)

**Comment by blewis** [comment]
Created another layer and now I see that I am not seeing any of the fields or values of the layers I create, just getting random values from the other layer.  
![image](https://user-images.githubusercontent.com/812849/57789644-52d9e980-7707-11e9-8e3f-cb0be2c45f20.png)

**Comment by blewis** [comment]
After saving the map again to the original name "bentest-1a" the URL remains in this form:  http://128.31.22.46/maps/add_layer?csrfmiddlewaretoken=jCpPcPnmti1dUpqi9zIuwvorsEPpmT2NjQcFsKX7KdX5U2WlXCm7xKZALayVxhcq&map_id=1818&layer_name=geonode%3Abentestlayer4

**Comment by blewis** [comment]
When I then open the actual map URL http://128.31.22.46/maps/1818/view I have the same problem.

**Comment by capooti** [comment]
> After saving the map again to the original name "bentest-1a" the URL remains in this form: http://128.31.22.46/maps/add_layer?csrfmiddlewaretoken=jCpPcPnmti1dUpqi9zIuwvorsEPpmT2NjQcFsKX7KdX5U2WlXCm7xKZALayVxhcq&map_id=1818&layer_name=geonode%3Abentestlayer4

@blewis this is expected. First time you save the url on the navigation bar won't change it. It will change the first time you access it from the maps list page.

**Comment by capooti** [comment]
@bglewis it looks like this layer is invalid as GeoNode didn't correctly add the attributes in the django database. For example check "Attributes" in the layer details page, there is nothing.
Do you remember if you got an error when creating this? Because I tried to create a layer just now and seems to work properly.

Your layer:

![Screenshot 2019-05-17 14 56 41](https://user-images.githubusercontent.com/148380/57950007-01bb2880-78b4-11e9-86e6-018dae132622.png)

My layer:

<img width="790" alt="Screenshot 2019-05-17 14 59 36" src="https://user-images.githubusercontent.com/148380/57950146-68d8dd00-78b4-11e9-8c43-7c67a77dabbb.png">

and my layer can now works correctly:

<img width="1042" alt="Screenshot 2019-05-17 15 00 44" src="https://user-images.githubusercontent.com/148380/57950194-902faa00-78b4-11e9-84b8-7a916953bd18.png">

**Comment by capooti** [comment]
I am closing this. By the way, when this happens it is enough to save the metadata, as I did now, which will resync django database with GeoServer. 
After that the attributes are correctly displayed again in the layer details page and in the identify dialog.
Not sure why that happened on the layer upload.

**Comment by blewis** [comment]
Could this be what is happening on camp production where they could not see attribute tables and control field order or which fields can be searched?

**Comment by capooti** [comment]
Yes, I remember they had a similar problem. I am not sure why this is happening, we would need  a way to replicate it. In any case, as said, by saving the metadata the fields will be synced again and identify will work again.
Or the administrator can run update_layers on all of the layers to fix things.
